import { useState } from "react";
import { newsItems } from "../data";

type ContentAudience = "Researcher" | "Teacher" | "Student" | "Public" | "Media";
type ContentChannel = "Article" | "Social Post" | "Short Video Script" | "Infographic Brief" | "Student Lesson";

const generatedContent: Record<ContentChannel, string> = {
  "Article": "DRAFT — AI Generated — Requires Editorial Review\n\n**46th Indian Antarctic Expedition Underway**\n\nThe National Centre for Polar and Ocean Research (NCPOR) has launched India's 46th Antarctic Expedition (46th IAE), marking a new chapter in the country's commitment to polar science. The expedition includes researchers from multiple disciplines including glaciology, oceanography, atmospheric science and marine biology.\n\nThe team will operate from India's two permanent Antarctic research stations, Maitri and Bharati, conducting multi-year climate observations, sea ice surveys and biodiversity assessments.\n\n[Source: 46th IAE Science Plan · NCPOR Expedition Archive · Status: DRAFT]\n[Review required before publication]",
  "Social Post": "DRAFT — AI Generated — Not approved for posting\n\n India's 46th Antarctic Expedition is now underway! Our scientists are heading to Maitri and Bharati stations to study sea ice, climate change and polar biodiversity.\n\nFollow along as we explore one of Earth's most remote frontiers. #NCPOR #AntarcticExploration #PolarScience #India\n\n[Source: NCPOR Expedition Archive · Status: DRAFT · Character count: 243]",
  "Short Video Script": "DRAFT — AI Generated — Requires Video Team Review\n\n[OPENING SHOT: Antarctic landscape, music builds]\n\nNARRATOR: Every year, Indian scientists venture to one of the most remote places on Earth...\n\n[SHOT: Maitri station exterior]\n\nNARRATOR: Antarctica. Home to India's two research stations — Maitri and Bharati — and the base for 46 scientific expeditions since 1981.\n\n[SHOT: Scientists working]\n\nNARRATOR: The 46th Indian Antarctic Expedition is now underway, studying sea ice, climate change and the mysteries of the Southern Ocean.\n\n[CLOSING SHOT: NCPOR logo]\n\n[Duration: ~60 seconds · Source: NCPOR Expedition Archive]",
  "Infographic Brief": "DRAFT — AI Generated — Requires Design Team Review\n\nINFOGRAPHIC BRIEF: 46th IAE at a Glance\n\nHEADLINE: India's 46th Antarctic Mission\nSUBHEAD: 42 years of polar exploration\n\nKEY STATS:\n• 42 total expeditions conducted\n• 2 permanent stations (Maitri + Bharati)\n• 350+ datasets collected\n• 1,200+ publications\n\nRECOMMENDED VISUALS: Antarctic landscape, station exteriors, map showing expedition routes, researcher photos\n\nSOURCE: NCPOR Expedition Archive · [Review required]",
  "Student Lesson": "DRAFT — AI Generated — Requires Educator Review\n\nLESSON PLAN: India Goes to Antarctica\nAge group: 10–14 years · Duration: 45 minutes\n\nLEARNING OBJECTIVES:\n• Understand why India conducts Antarctic expeditions\n• Identify India's research stations on a map\n• Explain two types of research conducted in Antarctica\n\nACTIVITY 1 (10 min): Map activity — locate Maitri and Bharati stations\nACTIVITY 2 (15 min): Watch the expedition launch video (link)\nACTIVITY 3 (10 min): Class discussion: Why is polar science important?\nQUIZ (10 min): 5 questions from NCPOR Polar Knowledge quiz bank\n\nSource: NCPOR Expedition Archive, Education Module\n[Requires educator review before classroom use]",
};

type WorkflowStatus = "DRAFT" | "SUBMITTED" | "UNDER_REVIEW" | "APPROVED" | "PUBLISHED";

const workflowSteps: WorkflowStatus[] = ["DRAFT", "SUBMITTED", "UNDER_REVIEW", "APPROVED", "PUBLISHED"];

const workflowLabels: Record<WorkflowStatus, string> = {
  DRAFT: "Draft", SUBMITTED: "Submitted", UNDER_REVIEW: "Under Review", APPROVED: "Approved", PUBLISHED: "Published"
};

function ContentStudio({ newsItem, onClose }: { newsItem: typeof newsItems[0]; onClose: () => void }) {
  const [audience, setAudience] = useState<ContentAudience>("Researcher");
  const [channel, setChannel] = useState<ContentChannel>("Article");
  const [generated, setGenerated] = useState(false);
  const [reviewStatus, setReviewStatus] = useState<WorkflowStatus>("DRAFT");
  const [studioTab, setStudioTab] = useState<"create" | "governance" | "audit">("create");
  const [auditLog, setAuditLog] = useState([
    { who: "System", action: "Content generated by AI", when: "Just now", status: "DRAFT" as WorkflowStatus },
  ]);

  const audiences: ContentAudience[] = ["Researcher", "Teacher", "Student", "Public", "Media"];
  const channels: ContentChannel[] = ["Article", "Social Post", "Short Video Script", "Infographic Brief", "Student Lesson"];

  return (
    <div className="fixed inset-0 z-40 flex" style={{ background: "rgba(0,0,0,0.5)" }} onClick={onClose}>
      <div className="ml-auto w-full max-w-2xl h-full bg-white flex flex-col overflow-hidden shadow-2xl" onClick={e => e.stopPropagation()}>
        <div className="flex-shrink-0 p-4 border-b" style={{ borderColor: "var(--border)" }}>
          <div className="flex items-start justify-between mb-1">
            <div>
              <div className="text-[10px] font-semibold uppercase text-blue-600 mb-0.5">Content Studio — One Source, Many Audiences</div>
              <h2 className="font-bold text-sm" style={{ color: "var(--text-primary)" }}>Create from Source</h2>
            </div>
            <button onClick={onClose} className="text-slate-400" aria-label="Close">x</button>
          </div>
          {generated && (
            <div className="tab-bar mt-2">
              <button className={`tab-item flex-1 ${studioTab === "create" ? "active" : ""}`} onClick={() => setStudioTab("create")}> Create</button>
              <button className={`tab-item flex-1 ${studioTab === "governance" ? "active" : ""}`} onClick={() => setStudioTab("governance")}> Governance</button>
              <button className={`tab-item flex-1 ${studioTab === "audit" ? "active" : ""}`} onClick={() => setStudioTab("audit")}> Audit</button>
            </div>
          )}
          <div className="rounded-lg p-2.5 text-xs mt-2" style={{ background: "#f8fafc", border: "1px solid var(--border)" }}>
            <div className="text-[9px] uppercase font-semibold mb-0.5" style={{ color: "var(--text-muted)" }}>Source</div>
            <div className="font-medium" style={{ color: "var(--text-primary)" }}>{newsItem.title}</div>
            <div className="text-[10px]" style={{ color: "var(--text-muted)" }}>{newsItem.date} · {newsItem.category} · Source ID: news_{newsItem.id}</div>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto p-4 space-y-4">
          {/* Audience selector */}
          <div>
            <div className="text-xs font-semibold mb-2" style={{ color: "var(--text-primary)" }}>Target Audience</div>
            <div className="flex flex-wrap gap-2">
              {audiences.map(a => (
                <button key={a} onClick={() => setAudience(a)} className={`px-3 py-1.5 rounded-lg text-xs font-medium border transition-all ${audience === a ? "border-blue-400 bg-blue-50 text-blue-700" : "border-slate-200 text-slate-600 hover:border-slate-300"}`}>{a}</button>
              ))}
            </div>
          </div>

          {/* Channel selector */}
          <div>
            <div className="text-xs font-semibold mb-2" style={{ color: "var(--text-primary)" }}>Content Format</div>
            <div className="flex flex-wrap gap-2">
              {channels.map(c => (
                <button key={c} onClick={() => setChannel(c)} className={`px-3 py-1.5 rounded-lg text-xs font-medium border transition-all ${channel === c ? "border-blue-400 bg-blue-50 text-blue-700" : "border-slate-200 text-slate-600 hover:border-slate-300"}`}>{c}</button>
              ))}
            </div>
          </div>

          {/* Generate button */}
          {!generated && (
            <button className="btn-primary w-full" onClick={() => setGenerated(true)}>
               Generate {channel} for {audience}
            </button>
          )}

          {/* Generated content */}
          {generated && (
            <div>
              <div className="flex items-center justify-between mb-2">
                <div className="text-xs font-semibold" style={{ color: "var(--text-primary)" }}>Generated Content</div>
                <div className="flex gap-2">
                  <span className="tag tag-orange">{reviewStatus}</span>
                  <span className="tag">AI Generated</span>
                </div>
              </div>
              <div className="rounded-lg p-4 text-xs whitespace-pre-wrap leading-relaxed" style={{ background: "#fffbeb", border: "1px solid #fef08a", color: "#78350f" }}>
                {generatedContent[channel]}
              </div>
              <div className="mt-3 p-3 rounded-lg text-[10px]" style={{ background: "#f0fdf4", color: "#166534" }}>
                <div className="font-semibold mb-1">Provenance preserved</div>
                Source ID: news_{newsItem.id} · Generated for audience: {audience} · Channel: {channel} · Status: {reviewStatus} — must be reviewed and approved before publication. AI-generated content does not become official merely by existing.
              </div>
              <div className="mt-3 flex gap-2 flex-wrap">
                {reviewStatus === "DRAFT" && (
                  <button className="btn-primary btn-sm" onClick={() => {
                    setReviewStatus("SUBMITTED");
                    setAuditLog(l => [...l, { who: "Researcher", action: "Submitted for editorial review", when: "Just now", status: "SUBMITTED" }]);
                    setStudioTab("governance");
                  }}>Submit for Review →</button>
                )}
                <button className="btn-outline btn-sm">Save Draft</button>
                <button className="btn-outline btn-sm" onClick={() => { setGenerated(false); setReviewStatus("DRAFT"); setStudioTab("create"); setAuditLog([{ who: "System", action: "Content generated by AI", when: "Just now", status: "DRAFT" }]); }}>Regenerate</button>
              </div>
            </div>
          )}

          {generated && studioTab === "governance" && (
            <div className="space-y-4">
              <div>
                <div className="text-xs font-semibold mb-3" style={{ color: "var(--text-primary)" }}>Workflow Status</div>
                <div className="flex items-center gap-0 overflow-x-auto">
                  {workflowSteps.map((step, i) => {
                    const idx = workflowSteps.indexOf(reviewStatus);
                    const done = i < idx;
                    const active = i === idx;
                    return (
                      <div key={step} className="flex items-center flex-shrink-0">
                        <div className={`flex flex-col items-center`}>
                          <div className={`w-6 h-6 rounded-full flex items-center justify-center text-[10px] font-bold ${done ? "bg-green-500 text-white" : active ? "bg-blue-600 text-white" : "bg-slate-200 text-slate-400"}`}>
                            {done ? "OK" : i + 1}
                          </div>
                          <div className={`text-[9px] mt-1 text-center w-14 ${active ? "font-semibold text-blue-700" : done ? "text-green-700" : ""}`} style={{ color: active ? "#1d4ed8" : done ? "#16a34a" : "var(--text-muted)" }}>
                            {workflowLabels[step]}
                          </div>
                        </div>
                        {i < workflowSteps.length - 1 && <div className={`w-8 h-px flex-shrink-0 mb-4 ${done ? "bg-green-400" : "bg-slate-200"}`}/>}
                      </div>
                    );
                  })}
                </div>
              </div>

              <div className="card p-3 space-y-2">
                <div className="text-xs font-semibold" style={{ color: "var(--text-primary)" }}>Governance Rules</div>
                {[
                  { rule: "AI-generated content requires editorial review before publication", ok: true },
                  { rule: "Source provenance must be preserved (Source ID: news_" + newsItem.id + ")", ok: true },
                  { rule: "Content is marked DRAFT until approved by a Publisher", ok: reviewStatus !== "PUBLISHED" },
                  { rule: "Approval required from designated Reviewer", ok: reviewStatus === "APPROVED" || reviewStatus === "PUBLISHED" },
                ].map(r => (
                  <div key={r.rule} className="flex items-start gap-2 text-[10px]">
                    <span className={`flex-shrink-0 font-bold ${r.ok ? "text-green-600" : "text-amber-500"}`}>{r.ok ? "OK" : "PENDING"}</span>
                    <span style={{ color: "var(--text-secondary)" }}>{r.rule}</span>
                  </div>
                ))}
              </div>

              <div className="flex flex-wrap gap-2">
                {reviewStatus === "SUBMITTED" && (
                  <button className="btn-primary btn-sm" onClick={() => { setReviewStatus("UNDER_REVIEW"); setAuditLog(l => [...l, { who: "Editor (demo)", action: "Picked up for review", when: "Moments ago", status: "UNDER_REVIEW" }]); }}>
                    Begin Review (Editor)
                  </button>
                )}
                {reviewStatus === "UNDER_REVIEW" && (
                  <button className="btn-primary btn-sm" onClick={() => { setReviewStatus("APPROVED"); setAuditLog(l => [...l, { who: "Editor (demo)", action: "Approved — ready to publish", when: "Moments ago", status: "APPROVED" }]); }}>
                    Approve
                  </button>
                )}
                {reviewStatus === "APPROVED" && (
                  <button className="btn-primary btn-sm" onClick={() => { setReviewStatus("PUBLISHED"); setAuditLog(l => [...l, { who: "Publisher (demo)", action: "Published to official channel", when: "Moments ago", status: "PUBLISHED" }]); }}>
                    Publish
                  </button>
                )}
                {reviewStatus === "PUBLISHED" && (
                  <div className="text-xs font-semibold text-green-700 bg-green-50 px-3 py-1.5 rounded-lg">OK Published — content is live</div>
                )}
                <button className="btn-outline btn-sm">Request Changes</button>
              </div>
            </div>
          )}

          {generated && studioTab === "audit" && (
            <div className="space-y-3">
              <div className="text-xs font-semibold mb-2" style={{ color: "var(--text-primary)" }}>Editorial Audit Trail</div>
              <div className="space-y-2">
                {auditLog.map((entry, i) => (
                  <div key={i} className="flex items-start gap-3 p-2.5 rounded-lg" style={{ background: "#f8fafc" }}>
                    <div className="w-6 h-6 rounded-full bg-slate-200 flex items-center justify-center text-[10px] font-bold flex-shrink-0" style={{ color: "var(--text-secondary)" }}>
                      {entry.who.charAt(0)}
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center justify-between gap-2">
                        <span className="text-xs font-medium" style={{ color: "var(--text-primary)" }}>{entry.who}</span>
                        <span className="text-[9px]" style={{ color: "var(--text-muted)" }}>{entry.when}</span>
                      </div>
                      <div className="text-[10px] mt-0.5" style={{ color: "var(--text-secondary)" }}>{entry.action}</div>
                      <span className={`text-[9px] px-1.5 py-0.5 rounded-full font-semibold mt-1 inline-block ${entry.status === "PUBLISHED" ? "bg-green-100 text-green-700" : entry.status === "APPROVED" ? "bg-blue-100 text-blue-700" : "bg-amber-100 text-amber-700"}`}>{workflowLabels[entry.status]}</span>
                    </div>
                  </div>
                ))}
              </div>
              <div className="text-[10px]" style={{ color: "var(--text-muted)" }}>
                Audit trail is maintained per NCPOR content governance policy. All actions are logged and cannot be deleted.
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

interface NewsProps {
  onOpenSocial?: (initialTopic?: string, initialContent?: string) => void;
}

export default function News({ onOpenSocial }: NewsProps = {}) {
  const [tab, setTab] = useState("latest");
  const [contentStudio, setContentStudio] = useState<typeof newsItems[0] | null>(null);

  const pressReleases = [
    { title: "NCPOR Signs MOU with SCAR for Enhanced Polar Collaboration", date: "1 Jul 2024", category: "Press Release", thumb: "https://images.unsplash.com/photo-1486566584569-b9319dc74315?w=120&q=80", excerpt: "MOU signed to enhance data sharing and joint expeditions." },
    { title: "India's 46th Antarctic Expedition: Ministry of Earth Sciences Statement", date: "15 Jun 2024", category: "Press Release", thumb: "https://images.unsplash.com/photo-1766465405501-ab1cce22d097?w=120&q=80", excerpt: "Official statement on expedition launch and scientific objectives." },
    { title: "NCPOR Publishes Comprehensive Arctic Strategy 2030", date: "3 May 2024", category: "Press Release", thumb: "https://images.unsplash.com/photo-1504858700536-882c978a3464?w=120&q=80", excerpt: "Ten-year strategic plan for Arctic research and Himadri station expansion." },
  ];

  const socialHighlights = [
    { title: "Our scientists just witnessed a stunning Aurora Australis from Maitri station! ", date: "10 Aug 2024", platform: "Twitter/X", image: "https://images.unsplash.com/photo-1504858700536-882c978a3464?w=300&q=80", likes: "2.4K", shares: "847" },
    { title: "46th IAE team reaches Antarctica safely. Expedition begins! EXP", date: "5 Aug 2024", platform: "Twitter/X", image: "https://images.unsplash.com/photo-1551415923-a2297c7fda79?w=300&q=80", likes: "5.1K", shares: "1.2K" },
    { title: "New sea ice dataset released on our open data portal. Download now!", date: "1 Aug 2024", platform: "LinkedIn", image: "https://images.unsplash.com/photo-1486566584569-b9319dc74315?w=300&q=80", likes: "342", shares: "89" },
  ];

  const displayedItems = tab === "latest" ? newsItems : tab === "press" ? pressReleases : [];

  return (
    <div className="h-full overflow-y-auto" style={{ background: "var(--content-bg)" }}>
      <div className="p-6">
        <div className="mb-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <h1 className="page-header-title">Content Creation</h1>
            <p className="page-header-sub">Stay updated with the latest news, stories and media content.</p>
          </div>
          <button
            onClick={() => onOpenSocial?.()}
            className="btn-primary btn-sm flex items-center gap-1.5 self-start sm:self-auto shadow-sm"
            style={{ background: "linear-gradient(135deg, #1e40af 0%, #2563eb 100%)" }}
          >
            <span></span>
            <span>Syndicate to Socials</span>
          </button>
        </div>

        <div className="tab-bar w-fit mb-5">
          {[["latest","Latest News"],["press","Press Releases"],["social","Social Media Highlights"]].map(([id, label]) => (
            <button key={id} className={`tab-item ${tab === id ? "active" : ""}`} onClick={() => setTab(id)}>{label}</button>
          ))}
        </div>

        {(tab === "latest" || tab === "press") && (
          <div className="card divide-y" style={{ borderColor: "var(--border)" }}>
            {displayedItems.map((item, i) => (
              <div key={i} className="flex items-start gap-4 p-4 hover:bg-slate-50 transition-colors">
                <img src={item.thumb} alt={item.title} className="w-20 h-14 object-cover rounded-lg flex-shrink-0"/>
                <div className="flex-1 min-w-0">
                  <div className="flex items-start justify-between gap-2">
                    <h3 className="font-semibold text-sm" style={{ color: "var(--text-primary)" }}>{item.title}</h3>
                    <span className="tag flex-shrink-0">{item.category}</span>
                  </div>
                  {"excerpt" in item && <p className="text-xs mt-1 leading-relaxed" style={{ color: "var(--text-secondary)" }}>{(item as any).excerpt}</p>}
                  <div className="text-[10px] mt-1" style={{ color: "var(--text-muted)" }}>{item.date}</div>
                </div>
                <div className="flex gap-2 flex-shrink-0 items-center">
                  <button
                    className="btn-outline btn-sm text-blue-600 border-blue-200 hover:bg-blue-50 flex items-center gap-1"
                    onClick={() => onOpenSocial?.(item.title, "excerpt" in item ? (item as any).excerpt : item.title)}
                    title="Syndicate this news to Twitter, Facebook, Instagram, LinkedIn, etc."
                  >
                    <span></span>
                    <span>Syndicate</span>
                  </button>
                  <button className="btn-outline btn-sm" onClick={() => setContentStudio(newsItems[Math.min(i, newsItems.length - 1)])}>
                     Create
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}

        {tab === "social" && (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {socialHighlights.map((item, i) => (
              <div key={i} className="card overflow-hidden hover:shadow-md transition-shadow cursor-pointer">
                <img src={item.image} alt="Social" className="w-full object-cover" style={{ height: 150 }}/>
                <div className="p-4">
                  <div className="flex items-center gap-1.5 mb-2">
                    <span className="text-xs font-semibold" style={{ color: "var(--accent)" }}>@NCPOR_Official</span>
                    <span className="tag">{item.platform}</span>
                  </div>
                  <p className="text-xs leading-relaxed mb-3" style={{ color: "var(--text-primary)" }}>{item.title}</p>
                  <div className="flex items-center gap-4 text-[11px]" style={{ color: "var(--text-muted)" }}>
                    <span> {item.likes}</span><span> {item.shares}</span><span className="ml-auto">{item.date}</span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {contentStudio && <ContentStudio newsItem={contentStudio} onClose={() => setContentStudio(null)}/>}
    </div>
  );
}
