export const expeditions = [
  {
    id: 1,
    title: "46th IAE (2024)",
    subtitle: "46th Indian Antarctic Expedition",
    dates: "Nov 2024 – Mar 2025",
    year: 2024,
    region: "Antarctic",
    status: "Active",
    description: "Continued scientific exploration with focus on climate, ocean and atmospheric studies.",
    image: "https://images.unsplash.com/photo-1486566584569-b9319dc74315?w=400&q=80",
  },
  {
    id: 2,
    title: "45th IAE (2023)",
    subtitle: "45th Indian Antarctic Expedition",
    dates: "Nov 2023 – Mar 2024",
    year: 2023,
    region: "Antarctic",
    status: "Completed",
    description: "Key studies on sea ice, ecology and polar atmosphere.",
    image: "https://images.unsplash.com/photo-1672570289260-d430df31d893?w=400&q=80",
  },
  {
    id: 3,
    title: "44th IAE (2022)",
    subtitle: "44th Indian Antarctic Expedition",
    dates: "Nov 2022 – Mar 2023",
    year: 2022,
    region: "Antarctic",
    status: "Completed",
    description: "Expanded research on glaciers and Southern Ocean.",
    image: "https://images.unsplash.com/photo-1687904368738-ca6423635666?w=400&q=80",
  },
  {
    id: 4,
    title: "43rd IAE (2021)",
    subtitle: "43rd Indian Antarctic Expedition",
    dates: "Nov 2021 – Mar 2022",
    year: 2021,
    region: "Antarctic",
    status: "Completed",
    description: "Oceanographic surveys and atmospheric boundary layer studies.",
    image: "https://images.unsplash.com/photo-1551415923-a2297c7fda79?w=400&q=80",
  },
  {
    id: 5,
    title: "42nd IAE (2020)",
    subtitle: "42nd Indian Antarctic Expedition",
    dates: "Nov 2020 – Mar 2021",
    year: 2020,
    region: "Antarctic",
    status: "Completed",
    description: "Studies on sea-level rise, biodiversity and cosmic rays.",
    image: "https://images.unsplash.com/photo-1462888387064-2a2ea232edb8?w=400&q=80",
  },
  {
    id: 6,
    title: "41st IAE (2019)",
    subtitle: "41st Indian Antarctic Expedition",
    dates: "Dec 2019 – Mar 2020",
    year: 2019,
    region: "Antarctic",
    status: "Completed",
    description: "Comprehensive glaciology, meteorology and marine biology research.",
    image: "https://images.unsplash.com/photo-1766465405501-ab1cce22d097?w=400&q=80",
  },
  {
    id: 7,
    title: "Arctic 2023",
    subtitle: "Indian Arctic Expedition 2023",
    dates: "Jun 2023 – Aug 2023",
    year: 2023,
    region: "Arctic",
    status: "Completed",
    description: "Svalbard-based research at Himadri station on Arctic sea ice and climate.",
    image: "https://images.unsplash.com/photo-1504858700536-882c978a3464?w=400&q=80",
  },
  {
    id: 8,
    title: "Arctic 2022",
    subtitle: "Indian Arctic Expedition 2022",
    dates: "Jun 2022 – Aug 2022",
    year: 2022,
    region: "Arctic",
    status: "Completed",
    description: "Atmospheric aerosol and black carbon studies in the high Arctic.",
    image: "https://images.unsplash.com/photo-1766699623469-32a2c3b17a17?w=400&q=80",
  },
];

export const publications = [
  {
    id: 1,
    title: "Changing sea ice dynamics in the Southern Ocean",
    journal: "Journal of Glaciology",
    year: 2024,
    authors: "A. Sharma, R. Kumar et al.",
    thumb: "https://images.unsplash.com/photo-1486566584569-b9319dc74315?w=100&q=80",
    doi: "10.1017/jog.2024.001",
  },
  {
    id: 2,
    title: "Atmospheric composition over Antarctica",
    journal: "Environmental Research Letters",
    year: 2023,
    authors: "P. Verma, S. Singh et al.",
    thumb: "https://images.unsplash.com/photo-1672570289260-d430df31d893?w=100&q=80",
    doi: "10.1088/1748-9326/ac4b2a",
  },
  {
    id: 3,
    title: "Biodiversity assessment of Antarctic microbiome",
    journal: "Polar Biology",
    year: 2023,
    authors: "K. Mehta, T. Rao et al.",
    thumb: "https://images.unsplash.com/photo-1551415923-a2297c7fda79?w=100&q=80",
    doi: "10.1007/s00300-023-3100-2",
  },
  {
    id: 4,
    title: "Indian Arctic Ocean observations and future trends",
    journal: "Climate Dynamics",
    year: 2022,
    authors: "S. Iyer, M. Das et al.",
    thumb: "https://images.unsplash.com/photo-1504858700536-882c978a3464?w=100&q=80",
    doi: "10.1007/s00382-022-06123-5",
  },
  {
    id: 5,
    title: "Glacial mass balance at Dakshin Gangotri: 2010–2022",
    journal: "Annals of Glaciology",
    year: 2022,
    authors: "D. Nair, J. Pillai et al.",
    thumb: "https://images.unsplash.com/photo-1687904368738-ca6423635666?w=100&q=80",
    doi: "10.1017/aog.2022.15",
  },
  {
    id: 6,
    title: "Polar vortex dynamics and Southern Hemisphere climate",
    journal: "Geophysical Research Letters",
    year: 2024,
    authors: "R. Gupta, A. Patel et al.",
    thumb: "https://images.unsplash.com/photo-1462888387064-2a2ea232edb8?w=100&q=80",
    doi: "10.1029/2024GL001234",
  },
];

export const datasets = [
  {
    id: 1,
    title: "Antarctic Sea Ice Concentration (2023)",
    size: "2.1 GB",
    parameter: "Sea Ice",
    region: "Antarctica",
    category: "Remote Sensing",
    year: 2023,
    thumb: "https://images.unsplash.com/photo-1486566584569-b9319dc74315?w=100&q=80",
    format: "NetCDF",
  },
  {
    id: 2,
    title: "Atmospheric Measurements at Maitri (2022)",
    size: "850 MB",
    parameter: "Atmosphere",
    region: "Antarctica",
    category: "Climate",
    year: 2022,
    thumb: "https://images.unsplash.com/photo-1766465405501-ab1cce22d097?w=100&q=80",
    format: "CSV/HDF5",
  },
  {
    id: 3,
    title: "Ocean Temperature Profiles – Southern Ocean (2021)",
    size: "1.4 GB",
    parameter: "Oceanography",
    region: "Southern Ocean",
    category: "Temperature",
    year: 2021,
    thumb: "https://images.unsplash.com/photo-1672570289260-d430df31d893?w=100&q=80",
    format: "NetCDF",
  },
  {
    id: 4,
    title: "Glacier Mass Balance Data (2020)",
    size: "600 MB",
    parameter: "Cryosphere",
    region: "Antarctica",
    category: "Glaciers",
    year: 2020,
    thumb: "https://images.unsplash.com/photo-1687904368738-ca6423635666?w=100&q=80",
    format: "GeoTIFF",
  },
  {
    id: 5,
    title: "Arctic Sea Ice Extent – Himadri (2023)",
    size: "980 MB",
    parameter: "Sea Ice",
    region: "Arctic",
    category: "Remote Sensing",
    year: 2023,
    thumb: "https://images.unsplash.com/photo-1504858700536-882c978a3464?w=100&q=80",
    format: "NetCDF",
  },
];

export interface MediaItem {
  id: number;
  type: "photo" | "video" | "360";
  title: string;
  location: string;
  expedition: string;
  year: number;
  category: "Landscapes" | "Wildlife" | "Stations" | "Research";
  image: string;
  videoUrl?: string;
  duration?: string;
  date: string;
  coordinates: string;
  photographer: string;
  resolution: string;
  fileSize: string;
  format: string;
  likes: number;
  tags: string[];
  description: string;
  hotspots?: { id: string; label: string; x: number; y: number; info: string }[];
}

export const mediaItems: MediaItem[] = [
  {
    id: 1,
    type: "photo",
    title: "Antarctic Landscape & Nunatak",
    location: "Dronning Maud Land",
    expedition: "IAE 2024",
    year: 2024,
    category: "Landscapes",
    image: "https://images.unsplash.com/photo-1486566584569-b9319dc74315?w=800&q=80",
    date: "18 Jan 2024",
    coordinates: "70°45'S, 11°44'E",
    photographer: "Dr. K. Sharma (NCPOR)",
    resolution: "4000 × 2667 px",
    fileSize: "8.4 MB",
    format: "RAW / JPEG",
    likes: 42,
    tags: ["Nunatak", "Glaciology", "Dronning Maud", "Ice sheet"],
    description: "High-resolution panorama of jagged nunataks piercing the continuous Antarctic ice sheet under 24-hour summer daylight.",
  },
  {
    id: 2,
    type: "photo",
    title: "Maitri Research Team In Field",
    location: "Maitri Station",
    expedition: "IAE 2023",
    year: 2023,
    category: "Stations",
    image: "https://images.unsplash.com/photo-1766465405501-ab1cce22d097?w=800&q=80",
    date: "04 Feb 2023",
    coordinates: "70°45'58\"S, 11°43'56\"E",
    photographer: "Expedition Logistics Team",
    resolution: "3840 × 2160 px",
    fileSize: "6.8 MB",
    format: "JPEG",
    likes: 35,
    tags: ["Maitri", "Fieldwork", "Scientists", "NCPOR"],
    description: "Indian Antarctic Expedition scientific team inspecting ground instrumentation outside Maitri Station in Schirmacher Oasis.",
  },
  {
    id: 3,
    type: "photo",
    title: "Aurora Australis Over Schirmacher",
    location: "Antarctica",
    expedition: "IAE 2023",
    year: 2023,
    category: "Landscapes",
    image: "https://images.unsplash.com/photo-1504858700536-882c978a3464?w=800&q=80",
    date: "22 May 2023",
    coordinates: "70°46'S, 11°44'E",
    photographer: "Atmospheric Science Division",
    resolution: "4200 × 2800 px",
    fileSize: "9.1 MB",
    format: "TIFF / JPEG",
    likes: 89,
    tags: ["Aurora", "Geomagnetism", "Polar Night", "Space Weather"],
    description: "Vibrant emerald Aurora Australis ribbons captured during polar night monitoring of geomagnetic substorms.",
  },
  {
    id: 4,
    type: "photo",
    title: "Emperor Penguin Colony",
    location: "Weddell Sea",
    expedition: "IAE 2022",
    year: 2022,
    category: "Wildlife",
    image: "https://images.unsplash.com/photo-1551415923-a2297c7fda79?w=800&q=80",
    date: "14 Dec 2022",
    coordinates: "72°15'S, 35°20'W",
    photographer: "Polar Biology Division",
    resolution: "3840 × 2560 px",
    fileSize: "7.5 MB",
    format: "JPEG",
    likes: 124,
    tags: ["Emperor Penguins", "Fauna", "Breeding Colony", "Ecology"],
    description: "Emperor penguin adults and chicks congregating on multi-year fast ice in the eastern Weddell Sea corridor.",
  },
  {
    id: 5,
    type: "photo",
    title: "High-Altitude Glaciology Field Camp",
    location: "Antarctica",
    expedition: "IAE 2022",
    year: 2022,
    category: "Research",
    image: "https://images.unsplash.com/photo-1766699623469-32a2c3b17a17?w=800&q=80",
    date: "28 Jan 2022",
    coordinates: "71°30'S, 10°12'E",
    photographer: "Deep Ice Core Team",
    resolution: "3600 × 2400 px",
    fileSize: "5.9 MB",
    format: "JPEG",
    likes: 27,
    tags: ["Ice Core", "Drilling", "Field Camp", "Cryosphere"],
    description: "Temporary insulated survival domes and ice drilling rigs set up for 120-meter firn core extraction.",
  },
  {
    id: 6,
    type: "photo",
    title: "Fimbul Ice Shelf Front",
    location: "Weddell Sea",
    expedition: "IAE 2021",
    year: 2021,
    category: "Landscapes",
    image: "https://images.unsplash.com/photo-1462888387064-2a2ea232edb8?w=800&q=80",
    date: "11 Mar 2021",
    coordinates: "70°00'S, 00°15'W",
    photographer: "Oceanographic Survey Team",
    resolution: "4500 × 3000 px",
    fileSize: "10.2 MB",
    format: "RAW / JPEG",
    likes: 56,
    tags: ["Ice Shelf", "Glacier", "Ocean Interface", "Satellite Ground Truth"],
    description: "Vertical 40-meter blue ice cliff face where the massive floating ice shelf meets the open Southern Ocean.",
  },
  {
    id: 7,
    type: "photo",
    title: "Polar Research Vessel Ivan Papanin",
    location: "Southern Ocean",
    expedition: "IAE 2021",
    year: 2021,
    category: "Research",
    image: "https://images.unsplash.com/photo-1687904368738-ca6423635666?w=800&q=80",
    date: "19 Nov 2021",
    coordinates: "64°22'S, 20°10'E",
    photographer: "Voyage Command",
    resolution: "3840 × 2160 px",
    fileSize: "6.2 MB",
    format: "JPEG",
    likes: 49,
    tags: ["Icebreaker", "Vessel", "Logistics", "Southern Ocean"],
    description: "Chartered polar expedition vessel navigating dense pack ice while transporting fuel containers and scientific payloads.",
  },
  {
    id: 8,
    type: "photo",
    title: "Tabular Iceberg Calving Event",
    location: "Ross Sea",
    expedition: "IAE 2020",
    year: 2020,
    category: "Landscapes",
    image: "https://images.unsplash.com/photo-1672570289260-d430df31d893?w=800&q=80",
    date: "08 Feb 2020",
    coordinates: "75°12'S, 168°40'E",
    photographer: "Cryosphere Remote Sensing Group",
    resolution: "4096 × 2732 px",
    fileSize: "8.9 MB",
    format: "JPEG",
    likes: 67,
    tags: ["Iceberg", "Calving", "Ross Sea", "Climate Dynamics"],
    description: "Massive tabular iceberg measuring 14 km across, recently separated from the continental shelf margin.",
  },
  {
    id: 9,
    type: "photo",
    title: "Adélie Penguins & Skua Interaction",
    location: "Antarctica",
    expedition: "IAE 2020",
    year: 2020,
    category: "Wildlife",
    image: "https://images.unsplash.com/photo-1609385509807-f191a8dc2bd2?w=800&q=80",
    date: "17 Jan 2020",
    coordinates: "69°24'S, 76°11'E",
    photographer: "Biological Survey Unit",
    resolution: "3600 × 2400 px",
    fileSize: "5.4 MB",
    format: "JPEG",
    likes: 73,
    tags: ["Adélie Penguins", "Avian Fauna", "Larsemann Hills", "Ecology"],
    description: "Nesting Adélie penguins defending perimeter against predatory South Polar skuas near coastal rocky outcrops.",
  },
  {
    id: 10,
    type: "video",
    title: "Documentary: 45th Indian Antarctic Expedition",
    location: "Antarctica",
    expedition: "IAE 2023",
    year: 2023,
    category: "Research",
    image: "https://images.unsplash.com/photo-1551415923-a2297c7fda79?w=800&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    duration: "14:22",
    date: "15 Mar 2023",
    coordinates: "70°46'S, 11°44'E",
    photographer: "NCPOR Outreach Media Unit",
    resolution: "4K UHD (3840 × 2160)",
    fileSize: "1.4 GB",
    format: "MP4 / H.264",
    likes: 110,
    tags: ["Documentary", "Expedition", "Logistics", "Science Operations"],
    description: "Official documentary charting the deployment, scientific drilling operations, and winterover crew handover of the 45th IAE.",
  },
  {
    id: 11,
    type: "video",
    title: "Bharati Station Operational Systems & Helipad",
    location: "Prydz Bay",
    expedition: "IAE 2022",
    year: 2022,
    category: "Stations",
    image: "https://images.unsplash.com/photo-1766465405501-ab1cce22d097?w=800&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    duration: "08:45",
    date: "20 Dec 2022",
    coordinates: "69°24'28\"S, 76°11'14\"E",
    photographer: "Station Operations Command",
    resolution: "1080p FHD (1920 × 1080)",
    fileSize: "680 MB",
    format: "MP4 / AAC",
    likes: 83,
    tags: ["Bharati", "Larsemann Hills", "Helicopter Operations", "Radar"],
    description: "Operational footage illustrating containerized living modules, wastewater purification systems, and helicopter supply airlifts at Bharati Station.",
  },
  {
    id: 12,
    type: "360",
    title: "Maitri Station – 360° Virtual Tour",
    location: "Maitri, Antarctica",
    expedition: "IAE 2023",
    year: 2023,
    category: "Stations",
    image: "https://images.unsplash.com/photo-1486566584569-b9319dc74315?w=800&q=80",
    date: "12 Feb 2023",
    coordinates: "70°45'58\"S, 11°43'56\"E",
    photographer: "NCPOR Virtual Reality Team",
    resolution: "8192 × 4096 px (Equirectangular)",
    fileSize: "28.5 MB",
    format: "WebVR / JPEG Pan",
    likes: 195,
    tags: ["Virtual Tour", "Maitri Station", "360 VR", "Schirmacher Oasis"],
    description: "Full 360° panoramic scan of Maitri Station main living complex, Lake Priyadarshini water pump house, and meteorology dome.",
    hotspots: [
      { id: "h1", label: "Living Quarters Module", x: 28, y: 46, info: "Thermal insulated living containers accommodating up to 25 winterover scientists and winter support staff." },
      { id: "h2", label: "Meteorological Sensor Mast", x: 62, y: 38, info: "Continuously monitoring surface wind velocity, solar radiation, ozone levels, and boundary layer thermodynamics." },
      { id: "h3", label: "Lake Priyadarshini Pump Line", x: 82, y: 64, info: "Heated subterranean pipe system providing continuous freshwater supply from glacial Lake Priyadarshini." },
      { id: "h4", label: "Geomagnetic Observatory", x: 14, y: 55, info: "Isolated non-magnetic shelter housing fluxgate magnetometers and high-sensitivity auroral spectrometers." },
    ],
  },
  {
    id: 13,
    type: "360",
    title: "Bharati Station – 360° Virtual Tour",
    location: "Prydz Bay, Antarctica",
    expedition: "IAE 2022",
    year: 2022,
    category: "Stations",
    image: "https://images.unsplash.com/photo-1687904368738-ca6423635666?w=800&q=80",
    date: "05 Jan 2022",
    coordinates: "69°24'28\"S, 76°11'14\"E",
    photographer: "NCPOR Virtual Reality Team",
    resolution: "8192 × 4096 px (Equirectangular)",
    fileSize: "32.0 MB",
    format: "WebVR / JPEG Pan",
    likes: 210,
    tags: ["Bharati Station", "Larsemann Hills", "360 VR", "High-Tech Lab"],
    description: "Interactive 360° walkthrough of India's modern polar research station Bharati constructed with 134 prefabricated shipping containers on stilts.",
    hotspots: [
      { id: "b1", label: "Oceanography & Biology Laboratories", x: 32, y: 50, info: "State-of-the-art wet and dry scientific laboratories equipped for spectrophotometry, HPLC, and microbiology incubation." },
      { id: "b2", label: "Satellite Ground Receiving Station", x: 74, y: 32, info: "High-throughput X-band tracking radome providing real-time data relay to ISRO/NRSC Hyderabad." },
      { id: "b3", label: "Elevated Structural Stilts", x: 50, y: 72, info: "Aerodynamic station design elevated 4 meters above bedrock to prevent snow drift accumulation under 150 km/h blizzards." },
      { id: "b4", label: "Combined Heat & Power Generators", x: 88, y: 58, info: "Triple-redundant cogeneration diesel turbine plant with exhaust heat recovery for station climate control." },
    ],
  },
];

export const newsItems = [
  {
    id: 1,
    title: "46th Indian Antarctic Expedition Launched",
    date: "12 Aug 2024",
    category: "News",
    thumb: "https://images.unsplash.com/photo-1486566584569-b9319dc74315?w=120&q=80",
    excerpt: "NCPOR successfully launched the 46th Indian Antarctic Expedition, marking a new chapter in India's polar research journey.",
  },
  {
    id: 2,
    title: "New Dataset Released: Antarctic Sea Ice 2024",
    date: "5 Aug 2024",
    category: "Announcement",
    thumb: "https://images.unsplash.com/photo-1672570289260-d430df31d893?w=120&q=80",
    excerpt: "NCPOR releases comprehensive sea ice concentration dataset for the 2024 Antarctic summer season.",
  },
  {
    id: 3,
    title: "NCPOR at India Science Festival",
    date: "26 Jul 2024",
    category: "Event",
    thumb: "https://images.unsplash.com/photo-1766465405501-ab1cce22d097?w=120&q=80",
    excerpt: "NCPOR showcased its polar research activities and educational programs at the National India Science Festival.",
  },
  {
    id: 4,
    title: "New Research Paper Published",
    date: "20 Jul 2024",
    category: "Research",
    thumb: "https://images.unsplash.com/photo-1551415923-a2297c7fda79?w=120&q=80",
    excerpt: "New paper published in Nature Climate Change on the impact of Indian Ocean circulation on Antarctic ice sheet dynamics.",
  },
  {
    id: 5,
    title: "India Joins International Polar Year Initiative",
    date: "10 Jul 2024",
    category: "Announcement",
    thumb: "https://images.unsplash.com/photo-1504858700536-882c978a3464?w=120&q=80",
    excerpt: "India formally joins the International Polar Year 2032–2033 initiative through NCPOR.",
  },
];

export const events = [
  {
    id: 1,
    day: "15",
    month: "Sep",
    title: "Polar Science Webinar Series",
    location: "Online | 4:00 PM IST",
    type: "upcoming",
    description: "Monthly webinar series on polar science topics by NCPOR researchers.",
    action: "Register",
  },
  {
    id: 2,
    day: "02",
    month: "Oct",
    title: "World Polar Day Celebration",
    location: "NCPOR, Goa",
    type: "upcoming",
    description: "Annual celebration of World Polar Day with public lectures and exhibitions.",
    action: "Details",
  },
  {
    id: 3,
    day: "18",
    month: "Nov",
    title: "Polar Science Exhibition",
    location: "New Delhi | Vigyan Bhavan",
    type: "upcoming",
    description: "A week-long exhibition on India's polar research achievements.",
    action: "Details",
  },
  {
    id: 4,
    day: "20",
    month: "Dec",
    title: "Annual Polar Research Symposium",
    location: "IISc Bangalore",
    type: "upcoming",
    description: "Annual gathering of polar researchers from across India.",
    action: "Details",
  },
  {
    id: 5,
    day: "15",
    month: "Jun",
    title: "Arctic Science Week 2024",
    location: "Tromsø, Norway",
    type: "past",
    description: "India participated in Arctic Science Week with presentations on Himadri station research.",
    action: "Summary",
  },
  {
    id: 6,
    day: "22",
    month: "Apr",
    title: "Earth Day Polar Awareness Campaign",
    location: "Pan India",
    type: "past",
    description: "Schools across India participated in polar awareness activities organized by NCPOR.",
    action: "Report",
  },
];

export const educationCards = [
  {
    id: 1,
    title: "Polar Basics",
    description: "Explore the icy world and why it matters.",
    icon: "",
    color: "#eff6ff",
    accent: "#2563eb",
    image: "https://images.unsplash.com/photo-1486566584569-b9319dc74315?w=300&q=80",
    level: "Beginner",
  },
  {
    id: 2,
    title: "Climate Change",
    description: "How polar regions affect our planet.",
    icon: "",
    color: "#f0fdf4",
    accent: "#16a34a",
    image: "https://images.unsplash.com/photo-1672570289260-d430df31d893?w=300&q=80",
    level: "Intermediate",
  },
  {
    id: 3,
    title: "Biodiversity",
    description: "Unique life in extreme conditions.",
    icon: "EXP",
    color: "#faf5ff",
    accent: "#7c3aed",
    image: "https://images.unsplash.com/photo-1551415923-a2297c7fda79?w=300&q=80",
    level: "Beginner",
  },
  {
    id: 4,
    title: "Quizzes & Activities",
    description: "Test your knowledge and learn fun facts.",
    icon: "",
    color: "#fff7ed",
    accent: "#ea580c",
    image: "https://images.unsplash.com/photo-1504858700536-882c978a3464?w=300&q=80",
    level: "All levels",
  },
];
